### ISSUE TITLE
Go get 

### ISSUE THREAD

**Issue by jehannes** [Sadzeih/go-reddit#2]
i'm a starter at go, so i'm probably doing something wrong but when running "go get github.com/Sadzeih/go-reddit/v2"

i get the following:
go: github.com/Sadzeih/go-reddit/v2@upgrade (v2.2.0) requires github.com/Sadzeih/go-reddit/v2@v2.2.0: parsing go.mod:
        module declares its path as: github.com/vartanbeno/go-reddit/v2
                but was required as: github.com/Sadzeih/go-reddit/v2
                
could i get some advice on how to import the package?

**Comment by Sadzeih** [comment]
Hi, sorry I didn't see your issue before, no idea how I didn't receive an email.

This is now fixed in the newest version, the previous go module was still pointing to the original code (that I forked). Now it's pointing to this repo.

**Comment by dreamscached** [comment]
Still happens when trying to get with `go get github.com/Sadzeih/go-reddit`; what worked for me was `go get github.com/Sadzeih/go-reddit@<commit-hash>`
